[package]
edition = "2021"
name = "region-restriction-checker"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-recursion = "1.0.4"
actix-web = "4.3.1"
lazy_static = "1.4.0"
redis = { version = "0.22.3", default-features = false, features = ["tokio-comp", "connection-manager"] }
regex = "1.7.1"
reqwest = { version = "0.11.15", default-features = false, features = ["rustls-tls", "gzip", "json", "socks"] }
serde = {version = "1.0.158", default-features = false, features = ["derive"]}
serde_json = "1.0.94"
tokio = { version = "1.26.0", features = ["full"] }
