version: "3"

services:
  redis:
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data
    command:
      - redis-server
      - --save 120 1
  tor-proxy:
    image: 1337kavin/alpine-tor:latest
    restart: unless-stopped
    environment:
      - tors=15
  restriction-checker:
    image: 1337kavin/restriction-checker:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      - REDIS_URL=redis://redis:6379
      - PROXY=socks5://tor-proxy:5566
    depends_on:
      - redis
      - tor-proxy

volumes:
  redis_data: null